### ISSUE TITLE
Verified email state

### ISSUE THREAD

**Issue by effone** [mybbgroup/Isango#30]
As reported by @shade- 
Some gateways can return unverified emails. In that case make use of verification state returned alongwith.

**Comment by Eldenroot** [comment]
It is a shame that nowadays these "gateways" do not offer verified emails... these should not be included in oAuth2... OK, nevermind, we need to add an extra layer of security into Isango.

**Comment by yuliu** [comment]
> It is a shame that nowadays these "gateways" do not offer verified emails... these should not be included in oAuth2... OK, nevermind, we need to add an extra layer of security into Isango.

That would be pretty common in countries and areas that use other identifiers, such as Cellphone numbers or other SNS-related IDs. Also, it seems that OAuth 2 doesn't define what kind of identifiers are fetch or returned. It may only be an implementation define, I suppose.

Since an account in MyBB is distinct from others by its username, and email (less important), it's better to re-design the user set up process (MyBB user account insertion) in Isango. Related issue is #19. Looks like username and email might be all uncertain after Isango gets tokens from 3rd party "gateway"s.

**Comment by effone** [comment]
As much I know those who accepts and carries unverified emails returns the verification state in response. Plan is to make effective use of that value.
If any provider is found providing unverified email without the verification state in response: we should avoid those providers for good security reason.

**Comment by yuliu** [comment]
> As much I know those who accepts and carries unverified emails returns the verification state in response. Plan is to make effective use of that value.
> If any provider is found providing unverified email without the verification state in response: we should avoid those providers for good security reason.

Then, what about those who just don't use email? As far as I know, cellphone number is another way of verification. Some services provides verification by email and phone number or just only phone number.

Just like MyBB, it can verify user logging in by either username or email or both.
